version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: docker build
          no_output_timeout: 60m
          command: |
            e=1 && for i in {1..5}; do
              docker build -t djarecka/nipype_tutorial:$CIRCLE_BRANCH . \
              && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: docker run
          no_output_timeout: 90m
          command: |
            docker run -it --rm djarecka/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/test_notebooks.py
         