version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker build
          no_output_timeout: 60m
          command: |
            for i in {1..5}; do
              docker build -t miykael/nipype_tutorial:$CIRCLE_BRANCH . && break || sleep 15
            done
      - run:
          name: docker run
          no_output_timeout: 120m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest --nbval -v -s /home/neuro/nipype_tutorial/notebooks/basic_*.ipynb /home/neuro/nipype_tutorial/notebooks/introduction_*.ipynb /home/neuro/nipype_tutorial/notebooks/advanced_*.ipynb /home/neuro/nipype_tutorial/notebooks/example_preprocessing.ipynb /home/neuro/nipype_tutorial/notebooks/example_1stlevel.ipynb /home/neuro/nipype_tutorial/notebooks/example_normalize.ipynb /home/neuro/nipype_tutorial/notebooks/example_2ndlevel.ipynb /home/neuro/nipype_tutorial/notebooks/handson_preprocessing.ipynb /home/neuro/nipype_tutorial/notebooks/handson_analysis.ipynb