version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker build
          no_output_timeout: 60m
          command: |
            for i in {1..5}; do
              docker build -t miykael/nipype_tutorial:$CIRCLE_BRANCH . && break || sleep 15
            done
      - run:
          name: docker run
          no_output_timeout: 120m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/test_notebooks.py
